SET foreign_key_checks = 0;

DROP TABLE IF EXISTS `users`;
create table `users` (
`user_id` int(11) not null auto_increment,
`user_nm` varchar(255) not null,
`password` varchar(255) not null,
`user_email` varchar(255) not null,
`hikes` tinyint(1),
`tpark` tinyint(1),
`museum` tinyint(1),
`mall` tinyint(1),
`npark` tinyint(1),
`sports` tinyint(1),
`wpark` tinyint(1),
`landmark` tinyint(1),
`musicEvent` tinyint(1),
`make` varchar(255),
`model` varchar(255),
`chevron` tinyint(1),
`circlek` tinyint(1),
`citgo` tinyint(1),
`costco` tinyint(1),
`cumberland` tinyint(1),
`exxon` tinyint(1),
`frontier` tinyint(1),
`kum` tinyint(1),
`mobil` tinyint(1),
`race` tinyint(1),
`shell` tinyint(1),
`sams` tinyint(1),
`speedway` tinyint(1),
`sunoco` tinyint(1),
`wawa` tinyint(1),
`seven` tinyint(1),
`methanol` tinyint(1),
`gasoline` tinyint(1),
`diesel` tinyint(1),
`hydrogen` tinyint(1),
`charge` tinyint(1),
`biodiesel` tinyint(1),
primary key (`user_id`)
) engine=innodb;
